image: gitpod/workspace-full
checkoutLocation: gitpod-k3s
tasks:
  - name: prepare k3s
    command: |
      dev/gitpod/prepare-k3s.sh
  - name: kernel dev environment
    init: |
      sudo apt update -y
      sudo apt upgrade -y
      sudo apt update -y
      sudo apt install qemu qemu-system-x86 linux-image-generic libguestfs-tools sshpass netcat -y
      dev/gitpod/prepare-rootfs.sh
    command: |
      dev/gitpod/qemu.sh