# permissions for end users to view speakers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: speaker-viewer-role
rules:
- apiGroups:
  - talks.kubecon.na
  resources:
  - speakers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - talks.kubecon.na
  resources:
  - speakers/status
  verbs:
  - get
