# permissions for end users to edit speakers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: speaker-editor-role
rules:
- apiGroups:
  - talks.kubecon.na
  resources:
  - speakers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - talks.kubecon.na
  resources:
  - speakers/status
  verbs:
  - get
